In [2]:
import numpy as np

In [46]:
rounds = 6

grid = np.array([[0,1,1,0,0],
                 [0,1,0,0,0],
                 [0,1,0,0,0],
                 [0,0,0,0,0]])





def count_neighbours(grid, y, x):
    height = grid.shape[0]
    width = grid.shape[1]    
    # Ensure coords are within grid boundries
    start_row, end_row = max(x-1, 0), min(width, x+2)
    start_col, end_col = max(y-1, 0), min(height, y+2)
    subgrid = grid[start_col:end_col, start_row:end_row]    
    
    if grid[y][x] == 1:
        
        return np.count_nonzero(subgrid == 1) - 1
    else:
        return np.count_nonzero(subgrid == 1)
    


def life_or_death(grid, y, x):
    alive = grid[y][x]
    neighbour_count = count_neighbours(grid, y, x)
    # print("Assessing point:", grid[y][x])
    # print("Alive?:", alive)
    # print("neighbour_count:", neighbour_count)
    
    if alive:
        if 2 <= neighbour_count <= 3:
            # print("fate: 1 \n")
            return 1
        else:
            # print("fate: 0 \n")
            return 0
    else:
        if neighbour_count == 3:
            # print("fate: 1 \n")
            return 1
        else:
            # print("fate: 0 \n")
            return 0
    




def update_grid(grid):
    # check each index of grid
    height = grid.shape[0]
    width = grid.shape[1]
    
    new_grid = np.zeros((height, width))    
    for y in range(height):
        for x in range(width):
            new_grid[y][x] = life_or_death(grid, y, x)
            
    return new_grid





# Run a few rounds
for round_index in range(rounds+1):
    print('Round', round_index)
    print(grid) 
    
    grid = update_grid(grid)    
           
            


    

Round 0
[[0 1 1 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]]
Round 1
[[0. 1. 1. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Round 2
[[1. 1. 1. 0. 0.]
 [1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Round 3
[[1. 0. 1. 0. 0.]
 [1. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Round 4
[[0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Round 5
[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Round 6
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
